window.posts = [
  {
    id:"p1",
    user:"@axia",
    creator:"@axia",
    desc:"🔥 Preview exclusivo • 12s",
    src:"https://cdn.coverr.co/videos/coverr-the-street-1577/1080p.mp4",
    premium:true,
    following:true,
    fetish:"bdsm",
    tags:["bdsm", "preview", "luxo"],
    likes:128,
    success:38,
    fail:12,
    videoState:{ explicitness:0.86, dominance:0.74, novelty:0.62, intimacy:0.6, frustration:0.82 },
    duration:24,
    avgWatchTime:18,
    likeRate:0.62,
    commentRate:0.31,
    unlockRate:0.44,
    freshness:0.82,
    comments:[
      {user:"@f3t", text:"isso é só o começo 😈"},
      {user:"@vip", text:"desbloqueia logo 💎"}
    ]
  },
  {
    id:"p2",
    user:"@darkgirl",
    creator:"@darkgirl",
    desc:"💦 Sem censura • 18s",
    src:"https://cdn.coverr.co/videos/coverr-the-ocean-1579/1080p.mp4",
    premium:false,
    following:false,
    fetish:"voyeur",
    tags:["voyeur", "night"],
    likes:320,
    success:52,
    fail:20,
    videoState:{ explicitness:0.42, dominance:0.35, novelty:0.58, intimacy:0.55, frustration:0.3 },
    duration:18,
    avgWatchTime:15,
    likeRate:0.54,
    commentRate:0.28,
    unlockRate:0.0,
    freshness:0.74,
    comments:[
      {user:"@anon", text:"🔥🔥🔥"},
      {user:"@curioso", text:"qual o @ dela?"}
    ]
  },
  {
    id:"p3",
    user:"@luxxx",
    creator:"@luxxx",
    desc:"💎 Conteúdo VIP • 22s",
    src:"https://cdn.coverr.co/videos/coverr-blonde-in-the-taxi-1574/1080p.mp4",
    premium:true,
    following:false,
    fetish:"luxo",
    tags:["luxo", "vip"],
    likes:87,
    success:24,
    fail:18,
    videoState:{ explicitness:0.78, dominance:0.52, novelty:0.5, intimacy:0.63, frustration:0.7 },
    duration:22,
    avgWatchTime:17,
    likeRate:0.48,
    commentRate:0.22,
    unlockRate:0.37,
    freshness:0.68,
    comments:[
      {user:"@colecionador", text:"vale cada crédito"}
    ]
  },
  {
    id:"p4",
    user:"@neon",
    creator:"@neon",
    desc:"🎥 POV neon • 9s",
    src:"https://cdn.coverr.co/videos/coverr-lights-at-the-disco-5056/1080p.mp4",
    premium:false,
    following:true,
    fetish:"feet",
    tags:["neon", "rapid", "feet"],
    likes:510,
    success:110,
    fail:30,
    videoState:{ explicitness:0.55, dominance:0.44, novelty:0.82, intimacy:0.4, frustration:0.2 },
    duration:9,
    avgWatchTime:8,
    likeRate:0.71,
    commentRate:0.18,
    unlockRate:0.0,
    freshness:0.91,
    comments:[{user:"@fast", text:"scroll perfeito"}]
  }
];
